### ISSUE TITLE
Win32/Fuery.B!cl

### ISSUE THREAD

**Issue by ziebelje** [yanivka/RazerJS#1]
Windows defender marks RazerJS-master.zip as containing the following Trojan: Win32/Fuery.B!cl

**Comment by yanivka** [comment]
Yea I see what you mean I did a scan myself ([Virus Scan](https://www.virustotal.com/en/file/8c654dbae2e5a26ba7cc33ea06b4dab113a3e77912a3ce1636c34df8a996661e/analysis/1487937110/)), please take the time and read this section in readme file ([RazerJS Security](https://github.com/yanivka/RazerJS#security)).

This is happening because the app is not code-signed (so the app is not trusted) and it hooks up to your keyboard and mouse events (as I said in the readme file), antiviruses may see that actions as spying (trojan).

I can definitely say that there is nothing there.
And you have the source code, you can just take the source code and compile it on your computer.

If you want to use the app you can download the final (signed) official application, from the [Razer webside](https://www.razerzone.com), or by the links from the official [video](https://www.youtube.com/watch?v=FxS44V4MHXk&t=2s)
